# Example: Frontend-only CI/CD pipeline
#
# This shows a setup for a project with only a frontend:
# - Node.js frontend (S3 + CloudFront)
# - Per-PR preview deployments
# - No backend deployment
# - Lighthouse audits on PRs
# - OIDC authentication (no static AWS keys)
#
# Copy this file to your project at .github/workflows/ci.yml
# and adjust the values to match your setup.

name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: voidreamer/ci-templates/.github/workflows/test-node.yml@main
    with:
      working-directory: "."
      build: true

  lighthouse:
    if: github.event_name == 'pull_request'
    uses: voidreamer/ci-templates/.github/workflows/lighthouse.yml@main
    with:
      working-directory: "."

  # ── Per-PR Preview Deployments ──
  preview:
    if: github.event_name == 'pull_request'
    uses: voidreamer/ci-templates/.github/workflows/preview-deploy.yml@main
    with:
      preview-domain: previews.example.com
      preview-bucket: my-site-previews
      frontend-dir: "."
      aws-role-arn: arn:aws:iam::123456789012:role/github-actions-deploy
    secrets:
      PREVIEW_CLOUDFRONT_ID: ${{ secrets.PREVIEW_CLOUDFRONT_ID }}
      VITE_ENV_VARS: |
        VITE_API_URL=${{ secrets.API_URL_STAGING }}

  deploy-production:
    needs: [test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: voidreamer/ci-templates/.github/workflows/deploy-aws.yml@main
    with:
      environment: production
      terraform-state-key: prod/terraform.tfstate
      custom-domain: example.com
      app-name: MySite
      backend-type: none
      run-migrations: false
      frontend-dir: "."
      aws-role-arn: arn:aws:iam::123456789012:role/github-actions-deploy
    secrets:
      VITE_ENV_VARS: |
        VITE_API_URL=${{ secrets.API_URL }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
