# Example: Full-stack CI/CD pipeline using Void CI Templates
#
# This shows a complete setup for a project with:
# - Python backend (Lambda)
# - Node.js frontend (S3 + CloudFront)
# - Terraform infrastructure
# - Per-PR preview deployments (replaces staging branch)
# - Production deployment on main
# - Telegram notifications
# - OIDC authentication (no static AWS keys)
#
# Copy this file to your project at .github/workflows/ci.yml
# and adjust the values to match your setup.

name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    uses: voidreamer/ci-templates/.github/workflows/test-python.yml@main
    with:
      postgres: true
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}

  test-frontend:
    uses: voidreamer/ci-templates/.github/workflows/test-node.yml@main

  lighthouse:
    if: github.event_name == 'pull_request'
    uses: voidreamer/ci-templates/.github/workflows/lighthouse.yml@main

  # ── Per-PR Preview Deployments ──
  # Frontend-only previews that share the staging backend API.
  # Requires: terraform/preview-aws module applied once, then
  # set PREVIEW_CLOUDFRONT_ID secret from the terraform output.
  preview:
    if: github.event_name == 'pull_request'
    uses: voidreamer/ci-templates/.github/workflows/preview-deploy.yml@main
    with:
      preview-domain: previews.example.com
      preview-bucket: my-app-previews
      frontend-dir: frontend
      aws-region: us-east-1
      aws-role-arn: arn:aws:iam::123456789012:role/github-actions-deploy
    secrets:
      PREVIEW_CLOUDFRONT_ID: ${{ secrets.PREVIEW_CLOUDFRONT_ID }}
      VITE_ENV_VARS: |
        VITE_API_URL=${{ secrets.API_URL_STAGING }}
        VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}

  # ── Production Deploy ──
  deploy-production:
    needs: [test-backend, test-frontend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: voidreamer/ci-templates/.github/workflows/deploy-aws.yml@main
    with:
      environment: production
      terraform-state-key: prod/terraform.tfstate
      custom-domain: app.example.com
      health-check-url: https://app.example.com
      app-name: MyApp
      aws-role-arn: arn:aws:iam::123456789012:role/github-actions-deploy
    secrets:
      TERRAFORM_VARS: |
        TF_VAR_environment=prod
        TF_VAR_database_url=${{ secrets.DATABASE_URL }}
      VITE_ENV_VARS: |
        VITE_API_URL=${{ secrets.API_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

  # ── Mobile Builds (release tags only) ──
  android:
    needs: [test-frontend]
    if: startsWith(github.ref, 'refs/tags/')
    uses: voidreamer/ci-templates/.github/workflows/android-build.yml@main
    with:
      app-id: com.example.myapp

  # iOS builds use macOS runners which cost 10x minutes.
  # Gated to tags (releases) only to protect the free tier.
  # A single 10-min build = 100 minutes of your 2,000/month budget.
  ios:
    needs: [test-frontend]
    if: startsWith(github.ref, 'refs/tags/')
    uses: voidreamer/ci-templates/.github/workflows/ios-build.yml@main
    with:
      app-id: com.example.myapp
